"""add events, community_tags, and missing score columns

Revision ID: 2f48e562be39
Revises: 350654fb1a30
Create Date: 2026-06-24 12:05:57.477206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f48e562be39'
down_revision: Union[str, None] = '350654fb1a30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('events', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('movies', sa.Column('ritual_score', sa.Float(), nullable=True))
    op.add_column('movies', sa.Column('dread_score', sa.Float(), nullable=True))
    op.add_column('movies', sa.Column('documentary_score', sa.Float(), nullable=True))
    op.add_column('movies', sa.Column('realism_score', sa.Float(), nullable=True))
    op.add_column('movies', sa.Column('slow_burn_score', sa.Float(), nullable=True))
    op.add_column('movies', sa.Column('chaos_score', sa.Float(), nullable=True))
    op.add_column('movies', sa.Column('community_tags', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'community_tags')
    op.drop_column('movies', 'chaos_score')
    op.drop_column('movies', 'slow_burn_score')
    op.drop_column('movies', 'realism_score')
    op.drop_column('movies', 'documentary_score')
    op.drop_column('movies', 'dread_score')
    op.drop_column('movies', 'ritual_score')
    op.drop_column('movies', 'events')
    # ### end Alembic commands ###
