"""initial

Revision ID: 350654fb1a30
Revises: 
Create Date: 2026-06-23 14:23:09.655745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '350654fb1a30'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interactions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('movie_id', sa.String(), nullable=False),
    sa.Column('event', sa.Enum('SEARCHED', 'CLICKED', 'WATCHED_TRAILER', 'SAVED', 'SKIPPED', 'LIKED', 'DISLIKED', 'SHARED', 'WATCH_COMPLETE', 'WATCH_ABANDONED', name='interactionevent'), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tmdb_id', sa.String(), nullable=True),
    sa.Column('imdb_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('original_title', sa.String(), nullable=True),
    sa.Column('release_year', sa.Integer(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('runtime', sa.Integer(), nullable=True),
    sa.Column('director', sa.String(), nullable=True),
    sa.Column('cast', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('poster_url', sa.String(), nullable=True),
    sa.Column('trailer_url', sa.String(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('content_warnings', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('genres', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('themes', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('tone', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('style', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('pacing_score', sa.Float(), nullable=True),
    sa.Column('found_footage_score', sa.Float(), nullable=True),
    sa.Column('documentary_vibe_score', sa.Float(), nullable=True),
    sa.Column('occult_score', sa.Float(), nullable=True),
    sa.Column('psychological_score', sa.Float(), nullable=True),
    sa.Column('jump_scare_score', sa.Float(), nullable=True),
    sa.Column('gore_score', sa.Float(), nullable=True),
    sa.Column('novelty_score', sa.Float(), nullable=True),
    sa.Column('embedding_text', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('imdb_id'),
    sa.UniqueConstraint('tmdb_id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('liked_titles', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('disliked_titles', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('preferences', sa.JSON(), nullable=True),
    sa.Column('taste_vector', sa.ARRAY(sa.Float()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('movies')
    op.drop_table('interactions')
    # ### end Alembic commands ###
