"""add score_confidence json

Revision ID: ca9e2d35ffc9
Revises: 2f48e562be39
Create Date: 2026-06-24 12:56:45.830093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca9e2d35ffc9'
down_revision: Union[str, None] = '2f48e562be39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('score_confidence', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'score_confidence')
    # ### end Alembic commands ###
